#!/bin/bash
find * -type f -name '*.php' | (
  [ -z "$IGNORE" ] && exec cat
  exec grep -v "$IGNORE"
) | (
  rv=0
  while read php
  do
    echo -n "$php: "
    php -l "$php" || rv=1
  done
  exit $rv
)

wp_plug() {
  rv=0
  if [ -n "$TRAVIS_TAG" ] ; then
    # Make sure the version tag is updated...
    local f=$(grep -l 'Version: ' *.php)
    if grep -q "Version: $TRAVIS_TAG" $f ; then
      echo "$f: $(grep Version: $f)"
    else
      echo "$f: VERSION MISMATCH ($TRAVIS_TAG)!"
      echo "Found $(grep Version: $f)"
      rv=1
    fi
  fi
  return $rv
}

[ $# -gt 0 ] && "$@"
